main: kamilki.me.ksafe.KSafe
name: KSafe
version: @version@
author: Kamilkime
description: "A fully configurable item safe for your server"
website: "https://github.com/Kamilkime/KSafe"

commands:
  ksafe:
    aliases: [schowek, safe, kschowek]
    description: Open your item safe

permissions:
  ksafe.open:
    default: true
  ksafe.bypass.limit:
    default: op
  ksafe.bypass.supply:
    default: op
  ksafe.reload:
    default: op